import * as THREE from './vendor/three.module.js';
const $=id=>document.getElementById(id),canvas=$('game');
document.body.classList.add('menu');
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true})}catch(e){$('notice').textContent='無法啟用 3D 畫面，請使用支援 WebGL 的 Edge 或 Chrome。';throw e}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight,false);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x081722);scene.fog=new THREE.FogExp2(0x081722,.022);
const camera=new THREE.PerspectiveCamera(75,innerWidth/innerHeight,.08,130);camera.rotation.order='YXZ';camera.position.set(0,1.65,13);scene.add(camera);
scene.add(new THREE.HemisphereLight(0xbcecff,0x1e2830,2.1));const sun=new THREE.DirectionalLight(0xd0eeff,3);sun.position.set(8,15,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-20,right:20,top:20,bottom:-25,near:1,far:60});scene.add(sun);
const material=(color,metalness=.2,roughness=.6)=>new THREE.MeshStandardMaterial({color,metalness,roughness});
const metal=material(0x233d4a,.6),dark=material(0x0b1b25),white=material(0xbacdd0,.5),lime=new THREE.MeshBasicMaterial({color:0xb8ff66}),cyan=new THREE.MeshBasicMaterial({color:0x54e4ef});
function box(w,h,d,x,y,z,mat,parent=scene){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
box(32,.3,46,0,-.2,-5,material(0x142630));
const grid=new THREE.GridHelper(44,44,0x376071,0x213e4b);grid.position.set(0,-.035,-6);scene.add(grid);
box(32,7,.5,0,3.4,-26,dark);box(.5,7,46,-16,3.4,-3,dark);box(.5,7,46,16,3.4,-3,dark);
for(let x=-14;x<=14;x+=4){box(.1,6,.12,x,3,-25.68,cyan);box(3.7,.06,.14,x+1.9,5.8,-25.6,metal)}
for(let z=-24;z<=16;z+=5){box(.2,6,.24,-15.65,3,z,metal);box(.2,6,.24,15.65,3,z,metal);box(.09,.05,3.2,-15.3,.03,z,cyan);box(.09,.05,3.2,15.3,.03,z,cyan)}
for(let x=-12;x<=12;x+=6){box(.05,.015,36,x,.015,-5,metal);box(1.2,.02,.18,x,.026,7,lime)}
const signCanvas=document.createElement('canvas');signCanvas.width=1024;signCanvas.height=256;const ctx=signCanvas.getContext('2d');ctx.fillStyle='#162d39';ctx.fillRect(0,0,1024,256);ctx.fillStyle='#b8ff66';ctx.font='bold 104px Arial';ctx.textAlign='center';ctx.fillText('NEON RANGE',512,133);ctx.font='24px Arial';ctx.fillStyle='#a3c1ce';ctx.fillText('PRECISION TRAINING  /  SECTOR 01',512,196);const sign=new THREE.Mesh(new THREE.PlaneGeometry(12,3),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(signCanvas)}));sign.position.set(0,4.7,-25.65);scene.add(sign);
// Training targets are kept beyond the player's movement area.
const robots=[];const bases=[[-8,-6],[-4,-12],[0,-8],[4,-16],[8,-8]];
bases.forEach(([x,z],i)=>{const g=new THREE.Group();g.position.set(x,0,z);scene.add(g);const bodyMat=material(i%2?0x65b7c5:0xb2c779,.55,.35);const body=box(.85,1.05,.55,0,1.4,0,bodyMat,g);const head=box(.7,.55,.55,0,2.23,0,white,g);box(.54,.17,.035,0,2.25,.3,cyan,g);box(.45,.33,.025,0,1.46,.29,lime,g);for(const s of [-1,1]){box(.22,.68,.25,s*.61,1.42,0,white,g);box(.26,.57,.3,s*.25,.55,0,metal,g);box(.35,.16,.5,s*.25,.21,.07,white,g)}const ring=new THREE.Mesh(new THREE.TorusGeometry(.96,.025,8,40),cyan);ring.rotation.x=Math.PI/2;ring.position.y=.03;g.add(ring);box(2,.12,1.8,x,.02,z,metal);const r={g,x,z,body,head,active:true,respawn:0,i};g.traverse(o=>{if(o.isMesh)o.userData.robot=r});head.userData.head=true;robots.push(r)});
const gun=new THREE.Group();camera.add(gun);gun.position.set(.34,-.3,-.58);box(.21,.22,.6,0,0,0,metal,gun);box(.15,.12,.55,0,.13,-.06,white,gun);box(.12,.11,.38,0,.01,-.43,dark,gun);box(.025,.04,.48,-.11,.06,-.1,cyan,gun);box(.11,.3,.17,0,-.2,.14,dark,gun);const flash=new THREE.Mesh(new THREE.IcosahedronGeometry(.12,0),lime);flash.position.set(0,0,-.67);flash.visible=false;gun.add(flash);gun.traverse(o=>{o.castShadow=false});
let state='menu',mode='basic',score=0,hits=0,shots=0,remaining=60,ammo=12,reloading=0,cooldown=0,elapsed=0,feedbackLife=0,flashLife=0,yaw=0,pitch=0,locked=false,drag=false,sound=true,audio=null,manual=false;
const keys=new Set(),ray=new THREE.Raycaster(),zero=new THREE.Vector2(),effects=[];
function beep(freq,duration,volume=.04){if(!sound)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.45,audio.currentTime+duration);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch{}}
function hud(){ $('score').textContent=String(score).padStart(4,'0');$('ammo').textContent=ammo;$('accuracy').textContent=shots?Math.round(hits/shots*100)+'%':'—';$('time').innerHTML=Math.ceil(remaining)+'<span>秒</span>';$('timebar').style.width=remaining/60*100+'%';$('reload-label').textContent=reloading>0?'充能中…':'能量彈匣';document.body.classList.toggle('urgent',remaining<=10)}
function showOverlay(title,description,label){$('title').innerHTML=title;$('description').textContent=description;$('start').textContent=label;$('overlay').hidden=false;document.body.classList.add('menu');keys.clear();clearTouch();drag=false;gun.visible=false;$('start').focus()}
function reset(){score=hits=shots=0;remaining=60;ammo=12;reloading=cooldown=elapsed=feedbackLife=flashLife=0;keys.clear();yaw=pitch=0;camera.rotation.set(0,0,0);camera.position.set(0,1.65,13);robots.forEach(r=>{r.active=true;r.respawn=0;r.g.visible=true;r.g.position.set(r.x,0,r.z)});effects.splice(0).forEach(e=>{scene.remove(e.obj);e.obj.geometry.dispose();e.obj.material.dispose()});$('feedback').textContent='';$('hitmarker').style.opacity=0;flash.visible=false;$('results').hidden=true;hud()}
async function capture(){if(touchMode)return;try{if(canvas.requestPointerLock)await canvas.requestPointerLock();else throw Error('unsupported')}catch{document.querySelector('.hint').innerHTML='<b>W A S D</b> 移動 ／ 移動滑鼠 瞄準 ／ 左鍵 射擊 ／ R 換彈'}}
function play(){if(state!=='paused')reset();state='playing';$('overlay').hidden=true;document.body.classList.remove('menu');gun.visible=true;beep(520,.08);capture()}
function pause(){if(state!=='playing')return;state='paused';if(document.pointerLockElement)document.exitPointerLock();$('settings').hidden=false;showOverlay('稍作休息。<br><span>準備再出發。</span>','遊戲已暫停，剩餘時間與分數會保留。','繼續挑戰 →')}
function end(){state='ended';if(document.pointerLockElement)document.exitPointerLock();$('settings').hidden=false;$('results').hidden=false;$('results').innerHTML=`<div><strong>${score}</strong><small>總分</small></div><div><strong>${hits}</strong><small>命中次數</small></div><div><strong>${shots?Math.round(hits/shots*100):0}%</strong><small>命中率</small></div>`;showOverlay('挑戰完成。<br><span>每一次都更精準。</span>','換個模式再挑戰一次，看看能不能超越自己的成績。','再玩一次 →');beep(880,.3)}
function reload(){if(state!=='playing'||reloading||ammo===12)return;reloading=1.15;beep(180,.15);hud()}
function particles(p){for(let i=0;i<10;i++){const obj=new THREE.Mesh(new THREE.BoxGeometry(.06,.06,.06),new THREE.MeshBasicMaterial({color:i%2?0xb8ff66:0x54e4ef}));obj.position.copy(p);scene.add(obj);effects.push({obj,life:.55,v:new THREE.Vector3((Math.random()-.5)*4,Math.random()*3,(Math.random()-.5)*4)})}}
function shoot(){if(state!=='playing'||cooldown>0||reloading)return;if(!ammo){reload();return}ammo--;shots++;cooldown=.17;flashLife=.06;flash.visible=true;beep(260,.085,.035);camera.updateMatrixWorld();scene.updateMatrixWorld(true);ray.setFromCamera(zero,camera);const meshes=[];robots.filter(r=>r.active).forEach(r=>r.g.traverse(o=>{if(o.isMesh)meshes.push(o)}));const hit=ray.intersectObjects(meshes,false)[0];let point=ray.ray.at(50,new THREE.Vector3());if(hit){point=hit.point;const r=hit.object.userData.robot;r.active=false;r.g.visible=false;r.respawn=1.3;hits++;const bonus=hit.point.y>=1.95;score+=bonus?20:10;$('feedback').textContent=bonus?'精準命中 +20':'命中 +10';feedbackLife=.65;$('hitmarker').style.opacity=1;particles(point);beep(bonus?1000:700,.1,.06)}const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([camera.localToWorld(new THREE.Vector3(.3,-.25,-1)),point]),new THREE.LineBasicMaterial({color:0xb8ff66,transparent:true,opacity:.8}));scene.add(line);effects.push({obj:line,life:.065});hud();if(ammo===0)reload()}
function update(dt){if(state!=='playing')return;if(touchFire)shoot();elapsed+=dt;remaining=Math.max(0,remaining-dt);cooldown=Math.max(0,cooldown-dt);if(reloading>0){reloading=Math.max(0,reloading-dt);if(!reloading){ammo=12;beep(550,.05);hud()}}const speed=keys.has('ShiftLeft')?7:4.7;let x=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),z=(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0);x+=touchMove.x;z+=touchMove.z;const n=Math.max(1,Math.hypot(x,z));x/=n;z/=n;camera.position.x=THREE.MathUtils.clamp(camera.position.x+(x*Math.cos(yaw)+z*Math.sin(yaw))*speed*dt,-14.5,14.5);camera.position.z=THREE.MathUtils.clamp(camera.position.z+(-x*Math.sin(yaw)+z*Math.cos(yaw))*speed*dt,-2,16);if(keys.has('ArrowLeft'))yaw+=dt*1.3;if(keys.has('ArrowRight'))yaw-=dt*1.3;if(keys.has('ArrowUp'))pitch+=dt;if(keys.has('ArrowDown'))pitch-=dt;pitch=THREE.MathUtils.clamp(pitch,-1.25,1.25);camera.rotation.set(pitch,yaw,0);robots.forEach(r=>{if(!r.active){r.respawn-=dt;if(r.respawn<=0){r.active=true;r.g.visible=true}}r.g.position.x=r.x+(mode==='moving'?Math.sin(elapsed*(.65+r.i*.08)+r.i)*1.2:0)});flashLife-=dt;flash.visible=flashLife>0;gun.position.z=THREE.MathUtils.damp(gun.position.z,flashLife>0?-.46:-.58,20,dt);gun.rotation.x=reloading>0?-.45:0;feedbackLife-=dt;if(feedbackLife<=0){$('feedback').textContent='';$('hitmarker').style.opacity=0}for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.life-=dt;if(e.v){e.v.y-=dt*6;e.obj.position.addScaledVector(e.v,dt)}if(e.life<=0){scene.remove(e.obj);e.obj.geometry.dispose();e.obj.material.dispose();effects.splice(i,1)}}hud();if(remaining<=0)end()}
$('start').onclick=play;$('pause').onclick=pause;$('sound').onclick=()=>{sound=!sound;$('sound').textContent='音效 '+(sound?'開':'關')};$('fov').oninput=e=>{camera.fov=Number(e.target.value);camera.updateProjectionMatrix()};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{if(state==='paused')return;mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('selected',x===b))});
document.addEventListener('pointerlockchange',()=>{const was=locked;locked=document.pointerLockElement===canvas;if(was&&!locked&&state==='playing')pause()});
let lastMouse=null;
canvas.addEventListener('mouseenter',e=>{lastMouse={x:e.clientX,y:e.clientY}});
canvas.addEventListener('mouseleave',()=>{lastMouse=null});
document.addEventListener('mousemove',e=>{
  if(touchMode||state!=='playing'||(!locked&&e.target!==canvas)){lastMouse=null;return}
  let dx=e.movementX,dy=e.movementY;
  if(!locked){
    if(!lastMouse){lastMouse={x:e.clientX,y:e.clientY};return}
    dx=e.clientX-lastMouse.x;dy=e.clientY-lastMouse.y;
    lastMouse={x:e.clientX,y:e.clientY};
  }
  const s=Number($('sensitivity').value)*.002;
  yaw-=dx*s;pitch=THREE.MathUtils.clamp(pitch-dy*s,-1.25,1.25);
  camera.rotation.set(pitch,yaw,0);
});
canvas.addEventListener('mousedown',e=>{if(touchMode)return;if(e.button===0)shoot();if(e.button===2)drag=true});document.addEventListener('mouseup',()=>drag=false);canvas.addEventListener('contextmenu',e=>e.preventDefault());
document.addEventListener('keydown',e=>{if(state==='playing'&&['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.code==='KeyR')reload();if(e.code==='Escape')pause()});document.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight,false)});
let previous=0;renderer.setAnimationLoop(t=>{const dt=previous?Math.min((t-previous)/1000,.05):0;previous=t;if(!manual)update(dt);renderer.render(scene,camera)});
window.render_game_to_text=()=>JSON.stringify({state,mode,score,hits,shots,ammo,reloading,remaining,position:camera.position.toArray(),yaw,pitch,locked,targets:robots.map(r=>({active:r.active,x:r.g.position.x,z:r.z}))});
// Deterministic QA access is only available with ?qa=1.
if(new URLSearchParams(location.search).has('qa'))window.rangeQA={step(seconds){manual=true;for(let t=0;t<seconds;t+=.02)update(Math.min(.02,seconds-t));renderer.render(scene,camera)},aim(i,head=false){const r=robots[i];camera.lookAt(r.g.position.x,head?2.23:1.4,r.z);yaw=camera.rotation.y;pitch=camera.rotation.x;camera.updateMatrixWorld()},shoot,pause};
let touchMode=matchMedia('(pointer: coarse)').matches||navigator.maxTouchPoints>0;
const touchMove={x:0,z:0};let touchFire=false,movePointer=null,lookPointer=null,firePointer=null,lookLast=null;
function clearTouch(){touchMove.x=touchMove.z=0;touchFire=false;movePointer=lookPointer=firePointer=null;lookLast=null;$('stick').style.transform='translate(0px,0px)'}
function enableTouch(){touchMode=true;document.body.classList.add('touch');$('notice').textContent='左側搖桿移動 · 右側滑動瞄準 · 按住射擊連發 · 建議橫向遊玩';$('pause').textContent='暫停';$('sensitivity').parentElement.firstChild.textContent='瞄準靈敏度 ';}
if(touchMode)enableTouch();
document.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'&&!touchMode)enableTouch()},{capture:true});
function moveStick(e){const r=$('joystick').getBoundingClientRect(),radius=r.width*.32;let x=(e.clientX-r.left-r.width/2)/radius,z=(e.clientY-r.top-r.height/2)/radius;const len=Math.hypot(x,z);if(len>1){x/=len;z/=len}touchMove.x=Math.abs(x)<.08?0:x;touchMove.z=Math.abs(z)<.08?0:z;$('stick').style.transform=`translate(${x*radius}px,${z*radius}px)`;}
const joy=$('joystick');joy.onpointerdown=e=>{if(state!=='playing'||movePointer!==null)return;e.preventDefault();movePointer=e.pointerId;joy.setPointerCapture(e.pointerId);moveStick(e)};joy.onpointermove=e=>{if(e.pointerId===movePointer)moveStick(e)};
function releaseMove(e){if(e.pointerId!==movePointer)return;movePointer=null;touchMove.x=touchMove.z=0;$('stick').style.transform='translate(0px,0px)'}
joy.onpointerup=joy.onpointercancel=joy.onlostpointercapture=releaseMove;
const look=$('look-zone');look.onpointerdown=e=>{if(state!=='playing'||lookPointer!==null)return;e.preventDefault();lookPointer=e.pointerId;lookLast={x:e.clientX,y:e.clientY};look.setPointerCapture(e.pointerId)};look.onpointermove=e=>{if(e.pointerId!==lookPointer||!lookLast||state!=='playing')return;const sensitivity=Number($('sensitivity').value)*.004;yaw-=(e.clientX-lookLast.x)*sensitivity;pitch=THREE.MathUtils.clamp(pitch-(e.clientY-lookLast.y)*sensitivity,-1.25,1.25);lookLast={x:e.clientX,y:e.clientY};camera.rotation.set(pitch,yaw,0)};
function releaseLook(e){if(e.pointerId===lookPointer){lookPointer=null;lookLast=null}}look.onpointerup=look.onpointercancel=look.onlostpointercapture=releaseLook;
const fire=$('touch-fire');fire.onpointerdown=e=>{if(state!=='playing'||firePointer!==null)return;e.preventDefault();firePointer=e.pointerId;fire.setPointerCapture(e.pointerId);touchFire=true;shoot()};function releaseFire(e){if(e.pointerId===firePointer){touchFire=false;firePointer=null}}fire.onpointerup=fire.onpointercancel=fire.onlostpointercapture=releaseFire;
$('touch-reload').onclick=reload;
window.addEventListener('blur',clearTouch);window.addEventListener('resize',clearTouch);
gun.visible=false;hud();window.rangeReady=true;$('start').disabled=false;$('start').textContent='開始挑戰 →';
